In [1]:
import torch

In [2]:
x= torch.empty(8,4)
print(x)

tensor([[4.3984e+27, 1.0806e-32, 1.6604e+22, 3.0820e+35],
        [1.6605e+22, 1.3180e-14, 3.5562e-09, 2.7339e+20],
        [1.4586e-19, 7.3867e+20, 5.5043e-02, 1.8467e+20],
        [2.6798e+20, 1.4331e-19, 2.7530e+12, 7.5338e+28],
        [5.9288e+11, 6.1186e-04, 4.3988e+21, 7.5631e+28],
        [5.2839e-11, 4.4177e+27, 9.7374e+15, 1.6851e+22],
        [2.9003e+35, 1.6605e+22, 1.7108e+19, 7.1440e+31],
        [3.0982e+27, 2.5360e-12, 1.4583e-19, 2.8177e+20]])


In [3]:
x.shape

torch.Size([8, 4])

8*4 matrix(평균 5, 표준편차 0.5)

In [5]:
x=torch.empty(8,4).normal_(mean=5, std=0.5)
print(x)

tensor([[5.7995, 5.0283, 5.4562, 4.7368],
        [4.8784, 5.4897, 4.3480, 4.4068],
        [5.4207, 5.5574, 4.8719, 5.1565],
        [4.7335, 4.8755, 5.6484, 5.7921],
        [5.6206, 5.1910, 5.3555, 4.7211],
        [4.5752, 4.5332, 5.0034, 4.5790],
        [3.6896, 4.9553, 5.1444, 4.2731],
        [5.2473, 4.5344, 6.4868, 5.2100]])


random(8*4)

In [7]:
x=torch.randn(8,4)
print(x)

tensor([[ 1.0229, -1.4742, -1.1704, -0.3521],
        [ 0.5746, -0.2434,  1.2336, -0.0800],
        [ 0.7082, -0.5856, -0.2804,  1.5289],
        [ 1.4113,  0.7414, -0.2337,  0.5620],
        [ 0.1880, -1.4379, -0.7847,  0.9995],
        [ 0.1901, -1.8230, -0.8404,  0.0720],
        [-1.2039,  0.6541, -1.8921,  0.6347],
        [ 0.4420, -2.0083,  1.1501,  1.7550]])


0으로 초기화 된 5*5 matrix

In [8]:
x=torch.zeros(5,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


1로 초기화 된 5*5 matrix

In [12]:
x=torch.ones(5,5)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


list를 tensor로 변경

In [10]:
x=list([[1,2],[3,4]])

In [11]:
x=torch.tensor(x)
print(x)

tensor([[1, 2],
        [3, 4]])


type=float 인 matrix

In [13]:
x=torch.randn(5,5, dtype=torch.float)
print(x)

tensor([[ 0.1307,  0.6034, -0.8327, -0.2779,  0.0768],
        [-0.7653, -1.0755,  1.0229,  1.1113, -0.2866],
        [ 1.9468,  1.4070, -0.3585,  1.0399, -0.9630],
        [-0.1073,  0.5475, -0.9514, -0.5749, -0.2259],
        [-0.4136,  0.0083,  2.0829,  0.9454, -0.3061]])


차원 이해하기

In [27]:
x=torch.tensor([[[1,1,1],[2,2,2],[3,3,3]]])

In [29]:
#가장 안에 있는[]가 size 에서 맨 뒤. 가장 큰 틀[[]] 1개, 그 안에 [] 3개, 그 안에[3개]
x,x.shape

(tensor([[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]]),
 torch.Size([1, 3, 3]))

[100,50,20]차원의 matrix

In [15]:
x=torch.randn(100,50,20)
print(x)

tensor([[[-9.3339e-01,  5.8330e-01,  1.0503e+00,  ..., -1.3236e+00,
           8.5112e-01,  5.6565e-01],
         [-5.0902e-03,  1.2135e+00, -2.9079e-01,  ..., -2.6091e+00,
          -6.9356e-01, -2.9621e-01],
         [-5.9137e-01, -1.6306e+00, -3.1884e-01,  ...,  5.5626e-01,
           2.0125e-01, -1.2889e+00],
         ...,
         [ 4.4853e-01, -3.2480e-01, -6.7492e-01,  ...,  2.5590e+00,
           2.8858e+00,  6.7993e-01],
         [ 8.2916e-01,  3.8620e-01,  6.8066e-01,  ..., -8.2272e-01,
           6.8107e-02, -1.2411e+00],
         [ 1.3762e+00,  2.2632e+00,  1.1508e+00,  ..., -2.6176e-01,
          -1.3021e-01,  1.2115e+00]],

        [[-2.4947e+00, -1.1572e+00,  1.3183e+00,  ..., -1.3813e+00,
          -6.3712e-01,  1.1666e+00],
         [-1.8017e-01,  3.0420e-01,  6.3979e-01,  ..., -1.7017e+00,
           3.2155e-01,  1.0702e-01],
         [ 7.8582e-02,  5.8319e-01,  4.0775e-01,  ..., -1.5242e+00,
          -8.8893e-01,  7.7755e-01],
         ...,
         [-5.7644e-02,  1

위에서 만든 matrix 이용하여, [100,20] matrix 50개 생성(by using 'for')

In [16]:
x.shape

torch.Size([100, 50, 20])

In [17]:
for i in range(x.shape[1]):
    print(x[:,i,:])

tensor([[-0.9334,  0.5833,  1.0503,  ..., -1.3236,  0.8511,  0.5657],
        [-2.4947, -1.1572,  1.3183,  ..., -1.3813, -0.6371,  1.1666],
        [ 0.0589, -1.0402, -0.6965,  ...,  0.2666,  2.0640,  0.2936],
        ...,
        [-0.8769, -0.6648,  0.7980,  ...,  1.1301, -1.9839, -1.1451],
        [-1.3794,  0.9392, -0.8665,  ..., -1.4064,  1.3103,  1.1575],
        [-0.0288, -1.1966,  0.9963,  ...,  0.4094, -0.8454,  1.0152]])
tensor([[-0.0051,  1.2135, -0.2908,  ..., -2.6091, -0.6936, -0.2962],
        [-0.1802,  0.3042,  0.6398,  ..., -1.7017,  0.3216,  0.1070],
        [ 0.4895, -0.7078,  0.4587,  ...,  1.2933, -1.8968, -0.6306],
        ...,
        [-0.6123, -0.8256,  0.1931,  ...,  1.0843,  0.5036,  0.7953],
        [ 0.4182,  1.6798, -0.0619,  ...,  0.0567, -0.6584,  0.1843],
        [-0.5486, -0.9078, -1.0383,  ...,  0.8656,  1.0224, -1.3234]])
tensor([[-0.5914, -1.6306, -0.3188,  ...,  0.5563,  0.2013, -1.2889],
        [ 0.0786,  0.5832,  0.4077,  ..., -1.5242, -0.8889,  0

matrix 간의 합

In [30]:
x=torch.randn(5,3)
y=torch.randn(5,3)

In [31]:
#1
z=x+y
print(z)

tensor([[-2.1352, -1.1984,  0.5592],
        [-0.4101, -1.1269,  2.4632],
        [ 0.4775,  1.7661,  1.3722],
        [-2.3090, -0.6052, -0.4097],
        [-0.5468, -1.0758, -0.2935]])


In [32]:
#2
z=torch.add(x,y)
print(z)

tensor([[-2.1352, -1.1984,  0.5592],
        [-0.4101, -1.1269,  2.4632],
        [ 0.4775,  1.7661,  1.3722],
        [-2.3090, -0.6052, -0.4097],
        [-0.5468, -1.0758, -0.2935]])


In [33]:
#3
z=torch.empty(5,3)
torch.add(x,y,out=z)
print(z)

tensor([[-2.1352, -1.1984,  0.5592],
        [-0.4101, -1.1269,  2.4632],
        [ 0.4775,  1.7661,  1.3722],
        [-2.3090, -0.6052, -0.4097],
        [-0.5468, -1.0758, -0.2935]])
